//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carga_Masiva_Suma
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateAud
    {
        public int id { get; set; }
        public int affiliateid { get; set; }
        public int modifieduserid { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int statusid { get; set; }
        public int reasonsid { get; set; }
        public string comments { get; set; }
    }
}
