//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carga_Masiva_Suma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int cardID { get; set; }
        public string PAN { get; set; }
        public Nullable<int> pluginID { get; set; }
        public Nullable<int> merchantID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> brandID { get; set; }
        public string expdateCard { get; set; }
        public string cvv2Card { get; set; }
        public Nullable<int> status { get; set; }
        public string offset { get; set; }
        public string lastOffset { get; set; }
        public string printed { get; set; }
        public Nullable<int> batchprinted { get; set; }
        public System.DateTime carddate { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
