//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carga_Masiva_Suma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Cards = new HashSet<Card>();
            this.Corporations = new HashSet<Corporation>();
        }
    
        public int clientID { get; set; }
        public string nameClient { get; set; }
        public string CIDClient { get; set; }
        public string addressClient { get; set; }
        public string phoneClient { get; set; }
        public Nullable<int> statusClient { get; set; }
        public Nullable<int> fileid { get; set; }
        public string password { get; set; }
        public Nullable<int> enabled { get; set; }
        public Nullable<int> pwd_expired { get; set; }
        public Nullable<int> reminder_id { get; set; }
        public string reminder_answer { get; set; }
        public System.DateTime clientdate { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<Corporation> Corporations { get; set; }
    }
}
