//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carga_Masiva_Suma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporation
    {
        public Corporation()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int corporationID { get; set; }
        public string nname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string agentName { get; set; }
        public string rif { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
