//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfiliadoIntere
    {
        public AfiliadoIntere()
        {
            this.Afiliacions = new HashSet<Afiliaciones>();
        }
    
        public int Id { get; set; }
        public int IdAfiliado { get; set; }
        public short IdInteres { get; set; }
    
        public virtual ICollection<Afiliaciones> Afiliacions { get; set; }
        public virtual Interes Intere { get; set; }
    }
}
