//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliacion
    {
        public int Id { get; set; }
        public int IdAfiliado { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public System.DateTime FechaAfiliacion { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Estatus { get; set; }
        public byte IdRazonBloqueo { get; set; }
        public Nullable<byte> IdRazonRechazo { get; set; }
        public Nullable<byte> IdOcupacion { get; set; }
        public Nullable<byte> IdNacionalidad { get; set; }
    
        public virtual AfiliadoInteres AfiliadoIntere { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
        public virtual RazonBloqueo RazonBloqueo { get; set; }
        public virtual RazonRechazo RazonRechazo { get; set; }
        public virtual Store Store { get; set; }
    }
}
