//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditing
    {
        public int id { get; set; }
        public int objectid { get; set; }
        public int operationsid { get; set; }
        public int userid { get; set; }
        public System.DateTime creationdate { get; set; }
        public string originaldata { get; set; }
        public string changedata { get; set; }
        public string ipaddress { get; set; }
    }
}
