//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public short Id { get; set; }
        public short IdUsuario { get; set; }
        public short IdObjeto { get; set; }
        public byte IdOperacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Datos { get; set; }
        public string DatosOriginales { get; set; }
    
        public virtual ObjetoAuditoria ObjetoAuditoria { get; set; }
        public virtual OperacionAuditoria OperacionAuditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
