//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditLimit
    {
        public int id { get; set; }
        public int companyid { get; set; }
        public decimal credit { get; set; }
        public decimal balance { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public int creationuserid { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int modifieduserid { get; set; }
        public bool activecredit { get; set; }
    }
}
