//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Afiliacions = new HashSet<Afiliacion>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public byte type { get; set; }
        public string docnumber { get; set; }
        public string name { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string password { get; set; }
        public Nullable<int> questionid { get; set; }
        public string answer { get; set; }
    
        public virtual ICollection<Afiliacion> Afiliacions { get; set; }
    }
}
