//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public ESTADO()
        {
            this.CIUDADES = new HashSet<CIUDAD>();
        }
    
        public string COD_ESTADO { get; set; }
        public string DESCRIPC_ESTADO { get; set; }
    
        public virtual ICollection<CIUDAD> CIUDADES { get; set; }
    }
}
