//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public decimal NRO_TARJETA { get; set; }
        public int SUCURSAL { get; set; }
        public int POS { get; set; }
        public decimal FACTURA1 { get; set; }
        public System.DateTime FECHA { get; set; }
        public string HORA { get; set; }
        public Nullable<decimal> MONTO_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> PUNTOS_ACRED { get; set; }
        public Nullable<int> PUNTOS_CANJE { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NRO_DOCUMENTO { get; set; }
    }
}
