//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolPermisoes = new HashSet<RolPermiso>();
        }
    
        public short Id { get; set; }
        public string Texto { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public byte Orden { get; set; }
    
        public virtual ICollection<RolPermiso> RolPermisoes { get; set; }
    }
}
