//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parentid { get; set; }
        public string controller { get; set; }
        public string actions { get; set; }
        public int order_no { get; set; }
        public string tooltips { get; set; }
    }
}
