//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetoAuditoria
    {
        public ObjetoAuditoria()
        {
            this.Auditorias = new HashSet<Auditoria>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Auditoria> Auditorias { get; set; }
    }
}
