//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ocupacion
    {
        public Ocupacion()
        {
            this.Afiliacions = new HashSet<Afiliacion>();
        }
    
        public byte Id { get; set; }

        [Required(ErrorMessage = "* La Ocupación es Requerido.")]
        [RegularExpression(@"^[a-zA-Z''-'\s]*$", ErrorMessage = "* La Ocupación debe contener solo letras y mas de 3 caracteres.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "* El Nombre debe tener una longitud entre 3 y 50 caracteres.")]
        public string Nombre { get; set; }
    
        public virtual ICollection<Afiliacion> Afiliacions { get; set; }
    }
}
