//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARROQUIA
    {
        public PARROQUIA()
        {
            this.MUNICIPIOs = new HashSet<MUNICIPIO>();
            this.URBANIZACIONs = new HashSet<URBANIZACION>();
        }
    
        public string COD_PARROQUIA { get; set; }
        public string DESCRIPC_PARROQUIA { get; set; }
    
        public virtual ICollection<MUNICIPIO> MUNICIPIOs { get; set; }
        public virtual ICollection<URBANIZACION> URBANIZACIONs { get; set; }
    }
}
