//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos_Affiliate
    {
        public int photo_id { get; set; }
        public byte[] photo { get; set; }
        public string photo_type { get; set; }
        public int Affiliate_id { get; set; }
    }
}
