//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidCustomer
    {
        public PrepaidCustomer()
        {
            this.Orders = new HashSet<Order>();
            this.PrepaidBeneficiaries = new HashSet<PrepaidBeneficiary>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string rif { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime creationdate { get; set; }
        public int userid { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PrepaidBeneficiary> PrepaidBeneficiaries { get; set; }
    }
}
