//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reason
    {
        public int id { get; set; }

        [Required(ErrorMessage = "* EL Nombre es requerido.")]
        [RegularExpression(@"^[a-zA-Z''-'\s]*$", ErrorMessage = "* La Razón debe contener solo letras y mas de 3 caracteres.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "* La Razón debe contener solo letras y mas de 3 caracteres.")]
        public string name { get; set; }

        public string type { get; set; }
    }
}
