//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumaStatus
    {
        public SumaStatus()
        {
            this.Affiliates = new HashSet<Affiliate>();
            this.Orders = new HashSet<Order>();
            this.OrdersDetails = new HashSet<OrdersDetail>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string tablename { get; set; }
        public int value { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<Affiliate> Affiliates { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
