//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SumaEntities : DbContext
    {
        public SumaEntities()
            : base("name=SumaEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Afiliacion> Afiliaciones { get; set; }
        public virtual DbSet<AfiliadoInteres> AfiliadoIntereses { get; set; }
        public virtual DbSet<Auditoria> Auditorias { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Interes> Intereses { get; set; }
        public virtual DbSet<LogError> LogErrors { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Nacionalidad> Nacionalidades { get; set; }
        public virtual DbSet<ObjetoAuditoria> ObjetoAuditorias { get; set; }
        public virtual DbSet<Ocupacion> Ocupaciones { get; set; }
        public virtual DbSet<OperacionAuditoria> OperacionAuditorias { get; set; }
        public virtual DbSet<RazonAcreditacion> RazonAcreditaciones { get; set; }
        public virtual DbSet<RazonBloqueo> RazonBloqueos { get; set; }
        public virtual DbSet<RazonRechazo> RazonRechazos { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<RolPermiso> RolPermisos { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        //public virtual DbSet<UtilityValues> UtilityValues { get; set; }
    }
}


